import sys; import os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import *
print("=== P) remove a rock while RESTING AT THE BOTTOM ===")
it=new(1); f=frame(it)
for _ in range(6): f=act(it,"noop")
for tgt in [(6,8),(7,8),(8,8)]: f=act(it,tgt)
for _ in range(6): f=act(it,"noop")
print(" landed:", origin(f), rocks(f))
f=act(it,(6,13)); print(" click rock (6,13):", origin(f), rocks(f))
for t in range(8): f=act(it,"noop"); print(f"  noop{t+1}", origin(f), rocks(f))
print(show(f))
print("\n=== Q) remove a SECOND rock (down to 1) ===")
r=rocks(f)[0]; f=act(it,r); print(f" click {r}:", origin(f), rocks(f))
for t in range(8): f=act(it,"noop"); print(f"  noop{t+1}", origin(f), rocks(f))
