"""Static (source-level) characterisation of all 55 Autumn programs in autumn_programs_55.zip.

Every field below comes from reading the .sexp source; numbers that need the interpreter live in
probe_results_s1.json (probe55.py). Field legend:

  id        AutumnBench program ID if the program is in the public 20-program manifest (else None)
  mech      one-line mechanics summary
  inputs    which inputs do anything.  L/R/U/D = arrows, C = click
  click     what click location means: none (no handler) | global (location ignored) | button (only
            specific static cells) | object (clicking on game objects) | free (anywhere on grid)
  stoch     none | init (randomness only at reset) | event (random draw when some event fires)
            | step (fresh randomness every tick)
  passive   none | scripted (state-independent timers/oscillators) | conditional (only objects the
            player created move, e.g. falling water) | autonomous (state-dependent, always running)
  hidden    none | low | med | high  -- how much unrendered state matters, and how it is recoverable
  relational  none|low|med|high  -- rules over adjacency / containment / collision / counting
  quant     none|low|med|high  -- counters, thresholds, timers, velocities
  mode      True if the meaning of an input depends on a (possibly hidden) mode variable
  irrev     irreversibility / absorbing states
  dim       low|med|high  -- observation size (grid x objects x colours)
  bugs      program defects that change what is actually learnable
  tier      A core | B secondary/conditional | S stochastic (distributional scoring only) | X exclude
"""

G = [
 dict(name="ants", id="S2KT7", grid=16, bg="black",
  mech="2 ants step toward the nearest food each tick; a click spawns 2 food at random cells (click location ignored); food eaten on contact.",
  inputs="C", click="global", stoch="event", stoch_note="randomPositions on every click",
  passive="conditional", passive_note="ants only move while food exists",
  hidden="none", hidden_note="all state rendered", relational="med", rel_note="nearest-target chase",
  quant="none", mode=False, irrev="food removal", dim="low",
  bugs="seed 0 collapses randomPositions to (0,0)", prior="benchmark; CD never renders at seed 0; planning floor 100%",
  tier="S", why="stochastic spawn location; chase rule is deterministic and learnable with set-based/partial scoring"),
 dict(name="arc_slack", id=None, grid=16, bg="black",
  mech="7 particles (green/gold); clicking a particle makes it the sole 'active' one (no visual change); arrows move the active one; gray button toggles its colour, orange-red button deletes it.",
  inputs="LRUD C", click="object+button", stoch="none", stoch_note="",
  passive="none", passive_note="", hidden="med", hidden_note="active flag never rendered; recoverable from the last click (memory)",
  relational="none", rel_note="", quant="none", mode=True, irrev="deletion", dim="low",
  bugs="", prior="", tier="A", why="the disease 'click=select' pattern generalised: 7 selectable objects + 2 buttons; clean and deterministic"),
 dict(name="balloon", id=None, grid=16, bg="skyblue",
  mech="Click inside the basket to add a rock (click on a rock removes it); >=3 rocks make the balloon sink 1/tick, fewer make it rise 1/tick.",
  inputs="C", click="object", stoch="none", stoch_note="", passive="autonomous", passive_note="balloon drifts up/down until a border",
  hidden="low", hidden_note="'weight' bool is a threshold of the visible rock count", relational="med", rel_note="containment + count threshold",
  quant="med", mode=False, irrev="", dim="med", bugs="", prior="",
  tier="B", why="nice count-threshold physics but a 36-cell sprite, sky-blue background, and a 15-cell click surface"),
 dict(name="balls", id=None, grid=12, bg="black",
  mech="Two balls bounce diagonally off grid edges and each other; L/R move a 3-cell wall, click on the wall toggles it solid (white) so balls bounce off it.",
  inputs="LR C", click="object", stoch="none", stoch_note="", passive="autonomous", passive_note="balls always moving",
  hidden="med", hidden_note="ball direction (8-way) inferable from two consecutive frames; balls step one cell off-grid before bouncing",
  relational="med", rel_note="collision/reflection", quant="med", mode=False, irrev="", dim="low",
  bugs="edge test uses ==GRID_SIZE so balls leave the grid for one tick", prior="",
  tier="A", why="autonomous physics with a latent velocity and a player-controlled obstacle; needs a 2-frame window"),
 dict(name="bbq", id="27VWC", grid=7, bg="black",
  mech="Gas counter burns down while the fire is on, meat 'cooked' counter rises; clicking bbq toggles fire, fill button adds gas, clicking meat feeds a person (+1/-1/-2 health by doneness) and resets the meat.",
  inputs="C", click="object+button", stoch="none", stoch_note="", passive="autonomous", passive_note="counters tick every step but only cross a visible band occasionally",
  hidden="med", hidden_note="gas and cooked are integers rendered as 2 / 4 colour bands", relational="none", rel_note="",
  quant="high", mode=False, irrev="health can hit -1", dim="low", bugs="", prior="benchmark; CD ceiling 0.83; planning floor 20%",
  tier="A", why="cleanest hidden-counter + threshold world; tiny grid keeps perception cheap"),
 dict(name="blicket", id=None, grid=11, bg="black",
  mech="Two blickets and a machine. Click a blicket to select/hide it, up/down change the selected blicket's shape (plus vs diagonal); the machine lights green iff (blicket1 is plus & visible) or (blicket2 is diagonal & visible).",
  inputs="UD C", click="object", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="low", hidden_note="'selected' is not rendered but follows the last click", relational="med", rel_note="boolean causal rule over two objects",
  quant="none", mode=True, irrev="", dim="low", bugs="", prior="",
  tier="A", why="blicket-detector causal discovery: a disjunctive 2-factor rule, deterministic, small; random play barely touches it (clicks 0.02) so it needs authored drives"),
 dict(name="block_breaker", id=None, grid=13, bg="black",
  mech="Ball bounces off edges and a 3-wide paddle (L/R); 20 balloons at random cells/colours are popped when the ball comes within 1 cell.",
  inputs="LR", click="none", stoch="init", stoch_note="balloon positions/colours drawn at reset only",
  passive="autonomous", passive_note="ball always moving", hidden="med", hidden_note="ball direction inferable from 2 frames",
  relational="med", rel_note="collision, proximity removal", quant="med", mode=False, irrev="balloon removal", dim="low",
  bugs="", prior="", tier="B", why="like balls but reset-time randomness means each seed is a different level; deterministic within a seed"),
 dict(name="bottle", id="ADA85", grid=11, bg="black",
  mech="Click Suzie/Billy to throw a rock that travels to the bottle over ~10 ticks; each rock secretly is/isn't a breaker (50/50, never rendered); click the broken bottle to mend it.",
  inputs="C", click="button+object", stoch="event", stoch_note="hidden coin flip per throw", passive="conditional", passive_note="rocks in flight",
  hidden="high", hidden_note="breaksBottle bit is unobservable until impact", relational="low", rel_note="", quant="none", mode=False,
  irrev="", dim="low", bugs="", prior="benchmark; flagship uncertainty game; planning floor 96%",
  tier="S", why="the only game that needs probabilistic planning; exact next-frame scoring is wrong here"),
 dict(name="buoyancy", id="NRDF6", grid=7, bg="black",
  mech="Click to drop a rock; rocks fall, water is displaced upward; each rock inside the crate sinks it one row (max 5).",
  inputs="C", click="free", stoch="none", stoch_note="", passive="conditional", passive_note="rocks fall, water settles over many ticks",
  hidden="low", hidden_note="addWeight equals visible rocks in crate", relational="high", rel_note="containment, displacement, stacking",
  quant="med", mode=False, irrev="", dim="low", bugs="", prior="benchmark; CD ceiling 0.20 (effect ~18 frames after click); planning floor 84%",
  tier="B", why="rich liquid physics but the action->effect chain is long; weak for h=1 objectives, decent for multistep"),
 dict(name="carrace", id=None, grid=13, bg="black",
  mech="Car advances one row every UPDATE_RATE ticks and obstacles descend; L/R steer, up/down change the speed (3..18); crash or finish resets the board and adds a score pip.",
  inputs="LRUD", click="none", stoch="none", stoch_note="", passive="scripted", passive_note="timer-driven motion",
  hidden="med", hidden_note="frame-phase and UPDATE_RATE are invisible; speed only shows as motion period", relational="low", rel_note="",
  quant="high", mode=False, irrev="episode resets", dim="low", bugs="obstacles never respawn until a reset", prior="",
  tier="B", why="tests timer-phase inference (like wind/space_invaders) without stochasticity; but the board resets itself"),
 dict(name="chaos_game", id=None, grid=50, bg="black",
  mech="Each click adds the midpoint between the last point and a uniformly random vertex (click location is ignored) - a Sierpinski chaos game.",
  inputs="C", click="global", stoch="event", stoch_note="random vertex per click + random start", passive="none", passive_note="",
  hidden="med", hidden_note="which point is 'last' is not visually marked", relational="low", rel_note="", quant="none", mode=False,
  irrev="", dim="high", bugs="start point is black on black", prior="",
  tier="X", why="50x50, click location irrelevant, every transition random; nothing deterministic to learn"),
 dict(name="charge", id=None, grid=7, bg="black",
  mech="A 2x2 jumper gains 1 energy every 3 ticks while grounded (cap 4); click launches it up by 'energy' cells, then gravity pulls it down; touching the top 'stop' toggles its colour. L/R move.",
  inputs="LR C", click="global", stoch="none", stoch_note="", passive="autonomous", passive_note="gravity + energy timer",
  hidden="high", hidden_note="energy never rendered; revealed by jump height", relational="low", rel_note="adjacency toggle",
  quant="high", mode=False, irrev="", dim="low", bugs="", prior="",
  tier="A", why="hidden accumulating resource with a timer, observable only through its effect; 7x7"),
 dict(name="chinese_checkers", id=None, grid=8, bg="black",
  mech="Click a peg to select it: legal jump targets (2 cells away over an occupied cell) light up yellow; click a target to jump.",
  inputs="C", click="object", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="low", hidden_note="active peg only shown via highlights", relational="high", rel_note="jump legality over the middle cell",
  quant="none", mode=True, irrev="", dim="low", bugs="", prior="",
  tier="B", why="clean relational rule with rendered affordances; very sparse random-click signal (must hit pegs)"),
 dict(name="chomp", id=None, grid=7, bg="black",
  mech="Click a block to select it and every block below-right of it (coloured by current player); the remove button deletes the selection and passes the turn; clicking the poisoned block ends the game.",
  inputs="C", click="object+button", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="low", hidden_note="current player is rendered on the player markers", relational="med", rel_note="quadrant selection",
  quant="none", mode=True, irrev="removal; game over", dim="low", bugs="", prior="",
  tier="A", why="2-player turn state + a geometric selection rule + irreversible removal, all on 7x7"),
 dict(name="coins", id="QFSVC", grid=16, bg="black",
  mech="Arrow-move an agent over coins to bank bullets (hidden counter); click fires a bullet upward if any are banked.",
  inputs="LRUD C", click="global", stoch="none", stoch_note="", passive="conditional", passive_note="bullets in flight",
  hidden="med", hidden_note="numBullets never rendered; agent can walk off-grid", relational="low", rel_note="pickup on overlap",
  quant="med", mode=False, irrev="coin removal", dim="low", bugs="", prior="benchmark; in current pipeline (qfsvc)",
  tier="A", why="hidden resource gates whether an action has any effect"),
 dict(name="colour_lines", id=None, grid=10, bg="black",
  mech="Click a ball to make it the mover; click an empty cell to set a destination (the mover walks there 1 cell/tick) AND spawn a random-coloured ball at a random cell.",
  inputs="C", click="object+free", stoch="event", stoch_note="new ball colour+position per empty click", passive="conditional", passive_note="mover walks to destination",
  hidden="med", hidden_note="moving flag and destination are not rendered", relational="low", rel_note="", quant="none", mode=True,
  irrev="", dim="low", bugs="", prior="",
  tier="S", why="deterministic walk-to-target is learnable but every empty click also injects a random ball"),
 dict(name="crystallization", id=None, grid=10, bg="black",
  mech="16 blue particles random-walk (no bounds); a particle adjacent to a red crystal becomes a crystal; click seeds a crystal.",
  inputs="C", click="free", stoch="step", stoch_note="random walk every tick", passive="autonomous", passive_note="",
  hidden="none", hidden_note="", relational="med", rel_note="adjacency contagion", quant="none", mode=False, irrev="crystallisation", dim="low",
  bugs="particles drift off-grid and are lost", prior="",
  tier="S", why="random walk like particles, plus a deterministic contagion rule worth scoring separately"),
 dict(name="diffusion", id=None, grid=9, bg="black",
  mech="Red and blue cells random-walk (4-way, no collision); 'up' cycles how many membrane segments exist (0..2); click adds red on the left half / blue on the right.",
  inputs="U C", click="free", stoch="step", stoch_note="random walk every tick", passive="autonomous", passive_note="",
  hidden="none", hidden_note="density rendered as membrane length", relational="low", rel_note="", quant="low", mode=False, irrev="", dim="low",
  bugs="", prior="", tier="S", why="pure random walk"),
 dict(name="dino", id=None, grid=20, bg="black",
  mech="Cactus and bird scroll left (bird re-enters at a random row); 'up' makes the dino jump 7 then fall 1/tick; any collision makes the dino invisible forever.",
  inputs="U", click="none", stoch="event", stoch_note="bird row on each wrap", passive="scripted", passive_note="scrolling obstacles",
  hidden="med", hidden_note="bird spawns off-screen (x=27) and is invisible for 8 ticks", relational="low", rel_note="collision", quant="low", mode=False,
  irrev="death is absorbing and unrendered thereafter", dim="low", bugs="", prior="",
  tier="B", why="one useful key, absorbing death; mostly a timing/reflex world"),
 dict(name="disease", id="DQ8GC", grid=16, bg="black",
  mech="Arrows move the active particle; clicking an inactive particle swaps which one is active (no visual change); sickness spreads to adjacent particles.",
  inputs="LRUD C", click="object", stoch="none", stoch_note="", passive="conditional", passive_note="contagion only when adjacent",
  hidden="med", hidden_note="which particle is active is never rendered", relational="high", rel_note="adjacency contagion",
  quant="none", mode=True, irrev="sickness", dim="low", bugs="MARA env transposes click args", prior="benchmark; core game in current pipeline",
  tier="A", why="already core; hidden selection + contagion"),
 dict(name="egg", id=None, grid=16, bg="gray",
  mech="Arrows move a 21-cell egg while gravity is off; the button toggles gravity (button colour shows it) and latches the egg's height - if the egg was above row 10 it shatters into gold pieces that fall.",
  inputs="LRUD C", click="button", stoch="none", stoch_note="", passive="conditional", passive_note="falling egg / pieces",
  hidden="low", hidden_note="latched height", relational="low", rel_note="", quant="med", mode=True, irrev="shatter", dim="med",
  bugs="", prior="", tier="B", why="good latched-threshold rule but a gray background and a large sprite"),
 dict(name="exp_particles", id=None, grid=16, bg="black",
  mech="Particles random-walk; click doubles every particle.", inputs="C", click="global", stoch="step", stoch_note="",
  passive="autonomous", passive_note="", hidden="none", hidden_note="", relational="none", rel_note="", quant="none", mode=False,
  irrev="", dim="low", bugs="CRASHES in the interpreter (updateObj lambda error) - unrunnable", prior="",
  tier="X", why="does not run"),
 dict(name="gameOfLife", id=None, grid=16, bg="black",
  mech="All 256 cells are particles (dead=black); click sets a cell alive; the green button applies one Conway step; the silver button clears.",
  inputs="C", click="free+button", stoch="none", stoch_note="", passive="none", passive_note="dynamics only on button press",
  hidden="none", hidden_note="", relational="high", rel_note="8-neighbour count rule", quant="med", mode=False, irrev="", dim="med",
  bugs="", prior="", tier="A", why="the only neighbourhood-counting rule in the corpus; the 'step' button is a perfectly observable action with a large effect"),
 dict(name="gravity_3", id="QQM74", grid=21, bg="black",
  mech="Arrows add -1/0/+1 to a shared x/y velocity; every blob moves by it each tick; click adds a blob. No bounds: blobs persist off-screen.",
  inputs="LRUD C", click="free", stoch="none", stoch_note="", passive="autonomous", passive_note="once velocity != 0",
  hidden="med", hidden_note="velocity only visible through motion; off-screen blobs invisible", relational="none", rel_note="",
  quant="med", mode=False, irrev="", dim="low", bugs="", prior="benchmark; pair-level ID vacuous; planning floor 100%",
  tier="B", why="arrow effect is one step delayed and saturates at |v|=1; off-screen state is unrecoverable"),
 dict(name="gravity", id="VQJH6", grid=17, bg="black",
  mech="Four edge buttons set the gravity direction; click adds a 2x2 blob; blobs move in the gravity direction each tick and persist off-screen.",
  inputs="C", click="free+button", stoch="none", stoch_note="", passive="autonomous", passive_note="",
  hidden="med", hidden_note="gravity mode invisible until a blob moves; off-screen blobs", relational="none", rel_note="",
  quant="none", mode=True, irrev="", dim="low", bugs="", prior="benchmark; planning floor 88%",
  tier="B", why="mode + off-screen hidden state; in pipeline already"),
 dict(name="grow", id="7XF97", grid=16, bg="black",
  mech="Cloud moves L/R, 'down' drops water; water reaching a green leaf grows a new leaf above it unless the sun overlaps the cloud; clicking the sun steps it (direction flips at edges).",
  inputs="LRD C", click="object", stoch="none", stoch_note="", passive="conditional", passive_note="falling water",
  hidden="low", hidden_note="sun's movingLeft bit", relational="med", rel_note="water-leaf contact gated by sun-cloud overlap",
  quant="none", mode=False, irrev="growth", dim="low", bugs="cloud can leave the grid", prior="benchmark; conditional tier",
  tier="A", why="multi-condition rule; already supported"),
 dict(name="hatch", id="AW9WD", grid=16, bg="black",
  mech="Click eggshell cells to break them; broken shells fall if unsupported or vanish when over a feather, revealing the hidden chick.",
  inputs="C", click="object", stoch="none", stoch_note="", passive="conditional", passive_note="falling shells",
  hidden="high", hidden_note="chick occluded; 'broken' flag invisible until a hole opens below", relational="med", rel_note="support/occlusion",
  quant="none", mode=False, irrev="", dim="low", bugs="", prior="benchmark; most headroom; hardest MFP",
  tier="A", why="exploration-reduced uncertainty; click effects mostly appear at t+2 and only bottom/over-feather shells do anything, so it needs authored drives"),
 dict(name="ice", id="BT3GB", grid=16, bg="black",
  mech="Cloud L/R, 'down' drops water that is liquid by day and ice by night; click toggles day/night and flips every drop.",
  inputs="LRD C", click="global", stoch="none", stoch_note="", passive="conditional", passive_note="falling/flowing water",
  hidden="none", hidden_note="", relational="med", rel_note="liquid flow", quant="none", mode=True, irrev="", dim="low",
  bugs="", prior="reference game", tier="A", why="reference / baseline"),
 dict(name="kaleidoscope", id=None, grid=25, bg="black",
  mech="Click places a 3-cell glitter of random colour; its mirror images in the other three quadrants are recomputed every tick.",
  inputs="C", click="free", stoch="event", stoch_note="colour per click", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="high", rel_note="4-fold reflective symmetry", quant="none", mode=False, irrev="", dim="high",
  bugs="reflections can land off-grid", prior="", tier="B", why="symmetry is a strong perception test, but colour is random and the grid is 25x25 with up to 346 cells"),
 dict(name="lightning_rod", id=None, grid=9, bg="black",
  mech="Cloud charge rises 1 every 3 ticks (3 colour bands); L/R move the cloud; clicking it resets charge and, if charge>=15, lights the rod gold for 20 ticks.",
  inputs="LR C", click="object", stoch="none", stoch_note="", passive="autonomous", passive_note="charge timer; rod countdown",
  hidden="high", hidden_note="exact charge, rod countdown and tick phase are invisible; clicking the cloud resets charge, which is only visible when the colour band drops", relational="none", rel_note="",
  quant="high", mode=False, irrev="", dim="low", bugs="", prior="",
  tier="A", why="banded counter + threshold-gated click + a 20-tick countdown: the temporal complement of bbq (L/R are the visible channel; most clicks are invisible resets)"),
 dict(name="lights_new", id=None, grid=24, bg="black",
  mech="Four click-switches drive three lamps through a fixed combinational rule (switch3 is a master, switch4 kills the supply permanently); wires are static decoration.",
  inputs="C", click="button", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="med", rel_note="boolean function of 4 switches", quant="low", mode=False,
  irrev="switch4 is permanent", dim="high", bugs="", prior="",
  tier="B", why="combinational-logic discovery but 115 static cells and an 8-cell click surface (1.4%)"),
 dict(name="lights", id="E3V6M", grid=16, bg="black",
  mech="A 5-cell bar: click toggles it on; when off arrows translate it, when on arrows rotate it through 8 orientations.",
  inputs="LRUD C", click="global", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="none", rel_note="", quant="low", mode=True, irrev="", dim="low",
  bugs="", prior="benchmark; recommended", tier="A", why="mode-dependent arrows, every action visible"),
 dict(name="lock", id=None, grid=9, bg="black",
  mech="Arrow-move a 2-cell key; when it sits in the keyhole the wall slides left one cell per tick - forever, off the grid.",
  inputs="LRUD", click="none", stoch="none", stoch_note="", passive="conditional", passive_note="wall slides while key is in place",
  hidden="none", hidden_note="", relational="low", rel_note="position trigger", quant="none", mode=False, irrev="wall leaves the grid", dim="low",
  bugs="wall never stops/returns (condition can never be met)", prior="",
  tier="X", why="one trigger, then a degenerate absorbing state"),
 dict(name="logic_gates", id=None, grid=24, bg="black",
  mech="Two click-switches; AND/OR/NOT/XOR outputs and wires light accordingly.",
  inputs="C", click="button", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="med", rel_note="boolean gates", quant="none", mode=False, irrev="", dim="high",
  bugs="", prior="", tier="X", why="only 4 reachable states; 99 static cells; 8-cell click surface"),
 dict(name="magnets", id="7WWW9", grid=16, bg="black",
  mech="Arrow-move a 2-cell magnet; when opposite poles line up 2 cells apart it is pulled one step; like poles adjacent cancel the move.",
  inputs="LRUD", click="none", stoch="none", stoch_note="", passive="conditional", passive_note="attraction step when aligned",
  hidden="none", hidden_note="", relational="high", rel_note="pole geometry", quant="none", mode=False, irrev="", dim="low",
  bugs="", prior="benchmark; dropped in audit (planning floor 40%)", tier="B", why="small state but a genuinely relational force rule"),
 dict(name="mario", id="N2NTD", grid=12, bg="white",
  mech="Platformer: gravity, L/R, jump when grounded; three platforms and an enemy oscillate; coins bank bullets (hidden), click fires.",
  inputs="LRU C", click="global", stoch="none", stoch_note="", passive="autonomous", passive_note="platforms/enemy always moving",
  hidden="med", hidden_note="bullet count; oscillation direction bits", relational="med", rel_note="collision/support",
  quant="med", mode=False, irrev="enemy death", dim="low", bugs="white background; CD first-click crash", prior="benchmark; n2ntd core",
  tier="A", why="richest agent+passive world already in the pipeline"),
 dict(name="masters_logic", id=None, grid=12, bg="black",
  mech="Mastermind: click guess cells to cycle colours, press enter to get 4 hint pegs (placed in random order); previous guesses scroll down.",
  inputs="C", click="object+button", stoch="init+event", stoch_note="code at reset; hint peg order per guess",
  passive="none", passive_note="", hidden="none", hidden_note="the 'secret' code is rendered from the start (show=true bug)",
  relational="med", rel_note="multiset comparison", quant="low", mode=False, irrev="", dim="low",
  bugs="CorrectAnswer.show initialised true - the code is visible", prior="",
  tier="X", why="the deduction is moot (answer visible) and hint placement is random"),
 dict(name="minesweeper", id=None, grid=10, bg="black",
  mech="100 hidden cells, each a mine w.p. 1/4 at reset; click reveals one (green safe / red mine); a revealed mine also reveals its 3x3 neighbourhood.",
  inputs="C", click="object", stoch="init", stoch_note="mine layout per seed", passive="conditional", passive_note="one-tick cascade after a mine",
  hidden="high", hidden_note="layout only recoverable by exploration", relational="low", rel_note="3x3 cascade", quant="none", mode=False,
  irrev="reveals", dim="med", bugs="no numbers/clues - it is a pure lottery", prior="",
  tier="S", why="deterministic within a seed (memorisable), unpredictable across seeds"),
 dict(name="nim", id=None, grid=17, bg="black",
  mech="Four rows of matches; click toggles a match selected; each row's red button removes that row's selected matches.",
  inputs="C", click="object+button", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="low", rel_note="row membership", quant="none", mode=False, irrev="removal", dim="low",
  bugs="", prior="", tier="B", why="paint-level control world with selection + per-row buttons"),
 dict(name="pacman", id=None, grid=10, bg="black",
  mech="Arrows move Pac-Man (walls block); two ghosts step toward him every 3rd tick; pellets vanish on contact.",
  inputs="LRUD", click="none", stoch="none", stoch_note="", passive="autonomous", passive_note="state-dependent chase on a 3-tick phase",
  hidden="med", hidden_note="tick phase (mod 3); score", relational="med", rel_note="chase; wall blocking",
  quant="low", mode=False, irrev="pellet removal", dim="low", bugs="ghost capture never kills (result unassigned) - non-terminating", prior="",
  tier="A", why="the corpus' only state-dependent autonomous pursuer; non-terminating thanks to the bug"),
 dict(name="paint", id="EAHCW", grid=16, bg="black",
  mech="Click paints a cell in the current colour; arrows set the colour (up gold, down purple, left green, right blue), the opposite arrow resets to red.",
  inputs="LRUD C", click="free", stoch="none", stoch_note="", passive="none", passive_note="",
  hidden="med", hidden_note="colour mode invisible until the next click", relational="none", rel_note="", quant="none", mode=True,
  irrev="", dim="low", bugs="", prior="benchmark; control world", tier="A", why="control"),
 dict(name="particles", id="83WKQ", grid=16, bg="black",
  mech="Click adds a particle; every particle random-walks one cell per tick.",
  inputs="C", click="free", stoch="step", stoch_note="", passive="autonomous", passive_note="", hidden="none", hidden_note="",
  relational="none", rel_note="", quant="none", mode=False, irrev="", dim="low", bugs="", prior="benchmark; stochastic",
  tier="S", why="irreducible random walk"),
 dict(name="peg_solitaire", id=None, grid=5, bg="black",
  mech="5x5 pegs with one hole; click a peg to select it (legal jumps turn pink), click a pink cell to jump and remove the middle peg. Initial selection is random among 4.",
  inputs="C", click="object", stoch="init", stoch_note="one of 4 starting selections", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="high", rel_note="jump legality", quant="none", mode=True, irrev="removal", dim="low",
  bugs="", prior="", tier="B", why="tiny relational puzzle with rendered affordances"),
 dict(name="ricochet_robots", id=None, grid=24, bg="black",
  mech="Click a robot to make it active (not rendered); an arrow launches it sliding until it hits a wall/robot.",
  inputs="LRUD C", click="object", stoch="none", stoch_note="", passive="conditional", passive_note="multi-tick slide after a launch",
  hidden="med", hidden_note="active robot; direction while sliding", relational="high", rel_note="slide-until-collision", quant="none", mode=True,
  irrev="", dim="high", bugs="", prior="",
  tier="B", why="best multi-step action effect in the corpus, but 24x24 with 159 static wall cells"),
 dict(name="rink", id=None, grid=28, bg="black",
  mech="A skater steps with arrows; stepping onto the 22x22 rink makes it slide 2 cells/tick in that direction until it leaves the ice.",
  inputs="LRUD", click="none", stoch="none", stoch_note="", passive="conditional", passive_note="sliding", hidden="low", hidden_note="slide direction",
  relational="low", rel_note="", quant="low", mode=False, irrev="", dim="high", bugs="skater can walk off the grid", prior="",
  tier="X", why="484 static cells for a 1-cell agent; momentum already covered by ricochet_robots"),
 dict(name="sand", id="VA6FQ", grid=10, bg="black",
  mech="Two buttons choose sand or water for clicks; water flows; sand touching water liquefies and flows too.",
  inputs="C", click="free+button", stoch="none", stoch_note="", passive="conditional", passive_note="flow",
  hidden="med", hidden_note="click-type mode", relational="high", rel_note="adjacency liquefaction, flow", quant="none", mode=True,
  irrev="liquefaction", dim="low", bugs="", prior="benchmark; conditional tier", tier="A", why="hidden mode + contagion + liquid physics on 10x10"),
 dict(name="scotland_yard", id=None, grid=20, bg="black",
  mech="Mr X moves along a fixed rail network: an arrow starts him moving and he keeps going until the next station.",
  inputs="LRUD", click="none", stoch="none", stoch_note="(uniformChoice helper is dead code)", passive="conditional", passive_note="auto-travel between stations",
  hidden="low", hidden_note="direction", relational="med", rel_note="graph adjacency", quant="none", mode=False, irrev="", dim="high",
  bugs="", prior="", tier="B", why="travel-to-station is a clean multi-step effect; 142 static cells"),
 dict(name="SET", id=None, grid=20, bg="black",
  mech="9 card slots refilled at random from only 3 card types; select 3 cards - they vanish if colours are all-same/all-different, otherwise deselect.",
  inputs="C", click="object", stoch="event", stoch_note="refill draws", passive="conditional", passive_note="refill 1 card/tick",
  hidden="none", hidden_note="", relational="med", rel_note="set rule", quant="none", mode=False, irrev="", dim="high",
  bugs="deck reduced to 3 cards; template cards rendered off-screen", prior="", tier="X", why="degenerate deck and random refills"),
 dict(name="snake", id=None, grid=16, bg="black",
  mech="Classic snake with wrap-around; arrows set direction; eating food grows the snake and respawns food at a random free cell. No death.",
  inputs="LRUD", click="none", stoch="event", stoch_note="food respawn", passive="autonomous", passive_note="always moving",
  hidden="low", hidden_note="direction", relational="med", rel_note="body following, wrap", quant="none", mode=False, irrev="growth", dim="low",
  bugs="", prior="", tier="B", why="almost deterministic (one random cell per meal) autonomous mover with growth"),
 dict(name="space_invaders", id="F5W3N", grid=16, bg="black",
  mech="Enemy rows oscillate on a 10-tick cycle; hero L/R, 'up' fires; every 15 ticks a random enemy fires downward.",
  inputs="LRU", click="none", stoch="event", stoch_note="shooter chosen every 15 ticks", passive="scripted", passive_note="oscillation",
  hidden="med", hidden_note="tick phase", relational="low", rel_note="collision", quant="low", mode=False, irrev="hero death", dim="low",
  bugs="", prior="benchmark; weak testbed", tier="S", why="periodic randomness"),
 dict(name="tetris", id=None, grid=16, bg="black",
  mech="Tetromino falls 1/tick; L/R move, up/down rotate; on landing a random piece spawns at a random column; no line clears; stack to the top ends play.",
  inputs="LRUD", click="none", stoch="event", stoch_note="piece shape+column per landing", passive="autonomous", passive_note="falling",
  hidden="none", hidden_note="", relational="med", rel_note="stacking/rotation collision", quant="none", mode=False, irrev="landing; top-out", dim="low",
  bugs="", prior="", tier="B", why="deterministic between landings; good rotation/collision rules"),
 dict(name="tictactoe", id=None, grid=5, bg="gray",
  mech="Click an empty board cell to place the current player's mark; play stops after a win or a full board.",
  inputs="C", click="object", stoch="none", stoch_note="", passive="none", passive_note="", hidden="low", hidden_note="turn parity",
  relational="low", rel_note="win lines", quant="none", mode=True, irrev="marks; game over", dim="low",
  bugs="winner border never renders", prior="", tier="X", why="<=9 transitions per episode; gray background"),
 dict(name="twiddle", id=None, grid=3, bg="black",
  mech="3x3 of 9 colours; clicking a corner rotates that 2x2 block clockwise. Starts one random rotation from solved.",
  inputs="C", click="button", stoch="init", stoch_note="1 of 4 scrambles", passive="none", passive_note="",
  hidden="none", hidden_note="", relational="high", rel_note="permutation", quant="none", mode=False, irrev="", dim="low",
  bugs="shuffle applies only one rotation (head of map)", prior="",
  tier="A", why="9-colour permutation rule on the smallest grid: a perception/belief sanity check"),
 dict(name="waterplug", id="NTQ4Y", grid=16, bg="black",
  mech="Buttons choose vessel/plug/water for clicks; water flows and is held by vessel walls and plugs; buttons also remove plugs or clear all.",
  inputs="C", click="free+button", stoch="none", stoch_note="", passive="conditional", passive_note="flow",
  hidden="med", hidden_note="click-type mode", relational="med", rel_note="flow/containment", quant="none", mode=True, irrev="", dim="med",
  bugs="", prior="benchmark; CD never fired in audit", tier="B", why="sand's sibling with more buttons; in pipeline"),
 dict(name="wind", id="DGG2C", grid=17, bg="black",
  mech="Every 5 ticks four drops spawn under the cloud and fall, drifting by the wind (-1/0/+1 set by L/R).",
  inputs="LR", click="none", stoch="none", stoch_note="", passive="scripted", passive_note="timer spawn + falling",
  hidden="med", hidden_note="wind only visible through drift; tick phase", relational="none", rel_note="", quant="med", mode=False,
  irrev="", dim="low", bugs="", prior="benchmark; dropped in audit", tier="B", why="arrow effects delayed one tick; timer gives free FD reward"),
]

BY_NAME = {g["name"]: g for g in G}
assert len(G) == 55, len(G)
